version: '3'
services:
  
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: news-aggregator-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: news-aggregator-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "1000:80"
      - "442:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: news-aggregator-db
    restart: unless-stopped
    tty: true
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_ROOT_PASSWORD: dbrootpw  # Set a strong password here
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    domainname: local
    container_name: news-aggregator-phpmyadmin
    restart: unless-stopped
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: dbrootpw  # Use the same password as above
      PMA_HOST: db
    ports:
      - "8091:80"
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local